package jdiskmark;

import javax.swing.DefaultComboBoxModel;

/**
 * "Advanced Options" dialog — currently exposes the Render Frequency Mode selector.
 * <p>
 * Access via the lazy-init singleton {@link Gui#getAdvancedFrame()} rather than
 * constructing directly.
 *
 * @author james, vpstackhub
 */
public class AdvancedOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates the form and populates the render-mode combo with all
     * {@link RenderFrequencyMode} values, selecting the current global setting.
     */
    public AdvancedOptionsFrame() {
        initComponents();
        setLocationRelativeTo(Gui.mainFrame);

        DefaultComboBoxModel<RenderFrequencyMode> model =
                new DefaultComboBoxModel<>(RenderFrequencyMode.values());
        renderModeCombo.setModel(model);
        renderModeCombo.setSelectedItem(App.rmOption);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        renderModeCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setTitle("Advanced Options");

        jLabel1.setText("Render Mode");

        renderModeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new RenderFrequencyMode[] { }));
        renderModeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderModeComboActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(renderModeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(renderModeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renderModeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderModeComboActionPerformed
        Object selected = renderModeCombo.getSelectedItem();
        if (selected instanceof RenderFrequencyMode mode) {
            App.rmOption = mode;
            App.saveConfig();
            Gui.refreshChartBadges();
        }
    }//GEN-LAST:event_renderModeComboActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<RenderFrequencyMode> renderModeCombo;
    // End of variables declaration//GEN-END:variables

}
