
package jdiskmark;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author james
 */
public class AdvancedOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedOptionsFrame
     */
    public AdvancedOptionsFrame() {
        initComponents();
        setLocationRelativeTo(Gui.mainFrame);
        DefaultComboBoxModel<RenderFrequencyMode> rModeModel
                = new DefaultComboBoxModel<>(RenderFrequencyMode.values());
        renderModeCombo.setModel(rModeModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        renderModeCombo = new javax.swing.JComboBox();

        setTitle("Advanced Options");

        jLabel1.setText("Render Mode");

        renderModeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        renderModeCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                renderModeComboMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(renderModeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(renderModeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renderModeComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renderModeComboMouseReleased
        try {
            App.rmOption = (RenderFrequencyMode) renderModeCombo.getSelectedItem();
        } catch (RuntimeException re) {
            System.err.print(" error casting item object" + re.getMessage());
        }
    }//GEN-LAST:event_renderModeComboMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox renderModeCombo;
    // End of variables declaration//GEN-END:variables
}
