
package jdiskmark;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.LinkedList;
import java.util.List;
import java.util.UUID;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class BenchmarkPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public BenchmarkPanel() {
    initComponents();
    Gui.runPanel = BenchmarkPanel.this;

    // Tooltip only – keep it simple
    runTable.setToolTipText("Mode: Write* means Write Sync was enabled");
    
    // #73 load new selected operation
    OperationTableSelectionListener selectionListener = new OperationTableSelectionListener(runTable);
    runTable.getSelectionModel().addListSelectionListener(selectionListener);

    // center align cells 2 - 11
    for (int i = 2; i <= 11; i++) {
        TableColumn c = runTable.getColumnModel().getColumn(i);
        c.setCellRenderer(new CenterTableCellRenderer());
    }

    // right align cell 12 (avg bw)
    TableColumn c = runTable.getColumnModel().getColumn(12);
    c.setCellRenderer(new RightTableCellRenderer());

    // auto scroll to bottom when a new record is added
    runTable.addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(ComponentEvent e) {
            runTable.scrollRectToVisible(
                runTable.getCellRect(runTable.getRowCount() - 1, 0, true)
            );
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        runTable = new javax.swing.JTable();

        runTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Drive Model", "Usage", "Type", "Order", "Samples", "Blocks (Size)", "Thread", "Start Time", "Time (ms)", "Lat (ms)", "Min/Max (MB/s)", "BW (MB/s)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        runTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(runTable);
        if (runTable.getColumnModel().getColumnCount() > 0) {
            runTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            runTable.getColumnModel().getColumn(1).setPreferredWidth(135);
            runTable.getColumnModel().getColumn(2).setPreferredWidth(46);
            runTable.getColumnModel().getColumn(2).setMaxWidth(45);
            runTable.getColumnModel().getColumn(3).setPreferredWidth(6);
            runTable.getColumnModel().getColumn(4).setPreferredWidth(40);
            runTable.getColumnModel().getColumn(5).setPreferredWidth(6);
            runTable.getColumnModel().getColumn(6).setPreferredWidth(35);
            runTable.getColumnModel().getColumn(7).setPreferredWidth(45);
            runTable.getColumnModel().getColumn(7).setMaxWidth(45);
            runTable.getColumnModel().getColumn(8).setPreferredWidth(80);
            runTable.getColumnModel().getColumn(9).setPreferredWidth(15);
            runTable.getColumnModel().getColumn(10).setPreferredWidth(10);
            runTable.getColumnModel().getColumn(11).setResizable(false);
            runTable.getColumnModel().getColumn(11).setPreferredWidth(50);
            runTable.getColumnModel().getColumn(12).setResizable(false);
            runTable.getColumnModel().getColumn(12).setPreferredWidth(32);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    static final int START_TIME_COLUMN = 7;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable runTable;
    // End of variables declaration//GEN-END:variables


    public void addRun(Benchmark run) {
        
        List<BenchmarkOperation> operations = run.getOperations();
        DefaultTableModel model = (DefaultTableModel) runTable.getModel();
        for (BenchmarkOperation o : operations) {
            model.addRow(
                    new Object[] {
                        run.getId(),
                        run.getDriveInfo().getDriveModel(),
                        run.getUsageColumnDisplay(),
                        o.getModeDisplay(),
                        o.blockOrder,
                        o.numSamples,
                        o.getBlocksDisplay(),
                        o.numThreads,
                        o.getStartTimeString(),
                        o.getDuration(),
                        o.getAccTimeDisplay(),
                        o.getBwMinMaxDisplay(),
                        o.getBwAvgDisplay(),
                    });
        }
    }
    
    public void hideFirstColumn() {
        TableColumnModel columnModel = runTable.getColumnModel();
        columnModel.removeColumn(columnModel.getColumn(0));
    }
    
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) this.runTable.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }
    
    public void deselect() {
        runTable.getSelectionModel().clearSelection();
    }
    
    // Get the selected benchmarks
    public List<UUID> getSelectedIds() {
        LinkedList<UUID> ids = new LinkedList<>();
        int[] selectedRows = runTable.getSelectedRows();
        // for each row get the benchmark id in the hidden column
        for (int r : selectedRows) {
            try {
                UUID benchmarkId = (UUID) runTable.getModel().getValueAt(r, 0);
                ids.add(benchmarkId);
            } catch (RuntimeException re) {
                System.err.println("Error retrieving id at row=" + r);
            }
        }
        return ids;
    }
}
