name: Build and Package

on:
  push:
    branches:
      - main
      - maven
  pull_request:
    branches:
      - main
      - maven

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Uncomment the line below if not commenting for troubleshooting
      # FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Ensure this line is correctly formatted
    - name: Set up JDK
      uses: actions/setup-java@v4  # Ensure this line is correctly formatted
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive ZIP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jdm-zip-distribution
        path: jdm-zip/target/*.zip
