name: Build and Package

on:
  push:
    branches:
      - main
      - maven
  pull_request:
    branches:
      - main
      - maven

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive ZIP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jdm-zip-distribution
        path: jdm-zip/target/*.zip
